# Generated by Django 4.0.5 on 2022-06-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='empId',
        ),
    ]
